name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        

    - name: Build
      run: |
        mkdir -p output
        go build -o ./output -v ./...
    
    - name: Compress Project
      run: |
        zip -r thriftgo.zip ./output

    - name: Create Tag
      id: create_tag
      run: |
        echo "::set-output name=release_tag::v_$(date +"%Y%m%d%H%M")"

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.create_tag.outputs.release_tag }}
        files: ./thriftgo.zip
    
      
